const DEFAULT_CODE = `    ; Write your Z80 code here

`;

const editor = document.getElementById('editor');
const explorer = document.getElementById('explorer');
const emulator = document.getElementById('emulator');

window.addEventListener('load', () => {
  explorer.openFile('hello.asm', 'examples/hello.asm');
});

explorer.addEventListener('open-file', (e) => {
  console.log('open-file', e);
  editor.openFile(e.detail);
});
explorer.addEventListener('new-file', (e) => {
  console.log('new-file', e);
  editor.openFile({
    name: undefined,
    text: ` ; Write your code here\n\n`,
  });
});
editor.addEventListener('file-saved', (e) => {
  console.log('file-saved');
  explorer.refreshUser();
});

function get_bytes(obj) {
  var bytes = [];
  obj.dump.forEach(function (entry) {
    if (!entry.lens) return;
    /* Concat the two arrays */
    bytes.push(...entry.lens);
  });
  return bytes;
}

async function assemble() {
  const code = editor.getValue();
  try {
    const result = await ASM.compile(code, { readFile: () => 0 }, { assembler: 'z80' });
    console.log('Assembly Result:', result);
    document.getElementById('log').className = 'log';
    document.getElementById('log').textContent = 'Assembly successful. Generated bytes:';
    const bytes = get_bytes(result);
    document.getElementById('hex-view').textContent = bytes.map((b) => b.toString(16).padStart(2, '0')).join(' ');
    return bytes;
  } catch (e) {
    const error = e.error;
    document.getElementById('log').className = 'log error';
    if (error.s) {
      document.getElementById('log').textContent = `❌ Error on line ${error.s.numline}: ${error.msg}`;
    } else {
      document.getElementById('log').textContent = '❌ Error: ' + error.msg;
    }
    console.error('❌ Assembly Error:', error);
    return [];
  }
}

async function code_run() {
  const bytes = await assemble();
  console.log(bytes);
  /* If we have some bytes, load them to the VFS */
  const data = new Uint8Array(bytes);

  emulator.reload(data);
}

async function code_stop() {
  emulator.stop();
}
